a = float(input("a: "))
b = float(input("b: "))
c = float(input("c: "))
d = float(input("d: "))
e = float(input("e: "))
f = float(input("f: "))
denominador = a * d - b * c
x = (e * d - b * f) / denominador
y = (a * f - e * c) / denominador
print("x =", x)
print("y =", y)
